stages:
    - init
    - test
    - build
    - run

before_script:
    - export GOROOT="/usr/local/go"
    - export GOPATH="/home/gitlab-runner/go"
    - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
    - export GOPROXY=direct
    - export Branch_Name="$CI_COMMIT_REF_NAME"
    - export Serivce_Name="cello"
    - export Build_Path="/home/gitlab-runner/tmp_build"
    - export GOOS="freebsd"

copy_dir:
    stage: init
    script:
    - make copy_dir
    - ln -sf $GOPATH/src/hcc/pb ../pb
    - ln -sf $GOPATH/src/hcc/hcc_errors ../hcc_errors


unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

code_coverage:
  stage: test
  script:
    - make coverage
#  only:
#  - master

go_report:
  stage: test
  script:
    - make goreport
#  only:
#  - master

#lint_code:
#  stage: test
#  script:
#    - make lint_dep
#    - make lint
build:
  stage: build
  script:
    - make
    - if [[ ! -d "$Build_Path/$Serivce_Name/$Branch_Name" ]]; then mkdir -p $Build_Path/$Serivce_Name/$Branch_Name;fi
    - cp -f $PWD/$Serivce_Name $Build_Path/$Serivce_Name/$Branch_Name/
    - echo "Build Complete"

service_run:
  stage: run
  script:
    - echo "Please regist storage Host"
    - sudo ssh -t root@storage "/usr/sbin/service $Serivce_Name stop"
    - sudo scp $Build_Path/$Serivce_Name/$Branch_Name/$Serivce_Name root@storage:/bin/$Serivce_Name
    - sudo ssh -t root@storage "chmod 755 /bin/$Serivce_Name"
    - sudo ssh -t root@storage "/usr/sbin/service $Serivce_Name start"
    - echo "Finished"
  only:
    - master
    - feature/dev

